### ISSUE TITLE
Payload cut on 0

### ISSUE THREAD

**Issue by sischnei** [1995parham/jrtp#1]
I'm not sure if you are still actively working on this. I was looking into your library to stream PCMA audio, however I noticed due to using 0 as termination indication in your serialization loop it is not possible to stream any audio actually containing a 0 byte.

I'm not a good C programmer, but I think providing the size of the array could solve the issue!?

I can make a PR if you are interested in maintaining your version!

**Comment by 1995parham** [comment]
Thank you for report this issue, I will check this and if you can make PR I will appreciate.

**Comment by 1995parham** [comment]
I correct this, please check my last commit.

**Comment by sischnei** [comment]
Looks great! Thank you! 

I'm not familiar how PlatformIO works, do you need to publish it as a new version to appear there?

**Comment by 1995parham** [comment]
Yes, I must publish it.

**Comment by 1995parham** [comment]
I changed the library version, we must wait until platfromio update the version
